name: pequelog
description: "Bitacora digital para peques."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.3
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  path: ^1.9.0
  shared_preferences: ^2.2.2
  go_router: ^14.6.2
  file_picker: ^8.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png

flutter_native_splash:
  color: "#FBFBF1"
  color_dark: "#3F4C5A"
  image: assets/logo.png
  image_dark: assets/logo.png
  android_12:
    color: "#FBFBF1"
    color_dark: "#3F4C5A"
    image: assets/logo.png
    image_dark: assets/logo.png
  ios_content_mode: center
  android_gravity: center

