import 'baby_action_kind.dart';

/// Immutable entity describing a recorded baby action.
class BabyAction {
  /// Builds a new [BabyAction] with the provided data.
  const BabyAction({
    required this.id,
    required this.babyId,
    required this.kind,
    required this.occurredAt,
    required this.details,
    this.notes,
  });

  /// Unique identifier generated by the persistence layer.
  final int id;

  /// Identifier of the baby this action belongs to.
  final int babyId;

  /// Kind of action that was registered.
  final BabyActionKind kind;

  /// Instant when the action happened.
  final DateTime occurredAt;

  /// Optional caregiver notes associated to the action.
  final String? notes;

  /// Additional structured data for the action.
  final Map<String, Object?> details;
}
