import 'baby_sex.dart';

/// Immutable domain entity representing a registered baby.
class Baby {
  /// Creates a new [Baby] instance with the provided attributes.
  const Baby({
    required this.id,
    required this.name,
    required this.birthDateTime,
    required this.sex,
    required this.birthLengthCm,
    required this.birthWeightKg,
    required this.photoPath,
  });

  /// Unique identifier generated by the persistence layer.
  final int id;

  /// Display name used across the app.
  final String name;

  /// Birth instant of the baby including date and time.
  final DateTime birthDateTime;

  /// Biological sex of the baby.
  final BabySex sex;

  /// Recorded birth length in centimeters.
  final double birthLengthCm;

  /// Recorded birth weight in kilograms.
  final double birthWeightKg;

  /// Optional local path to the baby portrait.
  final String? photoPath;
}
